site_name: Old Holden DIY
site_url: https://ocampco.github.io/old-holden-diy
site_description: Resource for the old Holden H-series
site_author: ocampco

repo_url: https://github.com/ocampco/old-holden-diy
repo_name: ocampco/old-holden-diy

theme:
  name: material
  palette:
    primary: white
    accent: red
  features:
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
  logo: ./assets/logo.png
  favicon: ./assets/logo.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      warning: material/key

extra_css:
  - ./assets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 0
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - admonition
  - pymdownx.details

plugins:
  - search
  - git-revision-date-localized
